-- Replace these example identities before interpreting the results.
WITH REQUIRED_JOBS
     (EXPECTED_JOB, EXPECTED_USER, EXPECTED_SUBSYSTEM) AS
(
    VALUES ('MYJOB1', 'MYUSER', 'MYSBS'),
           ('MYJOB2', 'MYUSER', 'MYSBS')
),
ACTIVE_JOBS AS
(
    SELECT JOB_NAME_SHORT, JOB_USER, SUBSYSTEM
    FROM TABLE(QSYS2.ACTIVE_JOB_INFO()) AS J
)
SELECT R.EXPECTED_JOB, R.EXPECTED_USER, R.EXPECTED_SUBSYSTEM,
       'REQUIRED JOB IS NOT ACTIVE' AS ALERT
FROM REQUIRED_JOBS AS R
WHERE NOT EXISTS
(
    SELECT 1 FROM ACTIVE_JOBS AS A
    WHERE A.JOB_NAME_SHORT = R.EXPECTED_JOB
      AND A.JOB_USER = R.EXPECTED_USER
      AND A.SUBSYSTEM = R.EXPECTED_SUBSYSTEM
);
