-- Example thresholds, not universal recommendations.
-- NULL/unknown capacities are excluded; production must track unknown too.
WITH STORAGE AS
(
    SELECT ASP_NUMBER,
           TOTAL_CAPACITY AS CAPACITY_MB,
           TOTAL_CAPACITY_AVAILABLE AS FREE_MB,
           DECIMAL(100.0 * (TOTAL_CAPACITY - TOTAL_CAPACITY_AVAILABLE)
                   / NULLIF(TOTAL_CAPACITY, 0), 7, 2) AS PERCENT_USED
    FROM QSYS2.ASP_INFO
    WHERE TOTAL_CAPACITY > 0
      AND TOTAL_CAPACITY_AVAILABLE >= 0
)
SELECT ASP_NUMBER, CAPACITY_MB, FREE_MB, PERCENT_USED,
       CASE WHEN PERCENT_USED >= 90 THEN 'CRITICAL'
            ELSE 'WARNING' END AS ALERT_LEVEL
FROM STORAGE
WHERE PERCENT_USED >= 80
ORDER BY PERCENT_USED DESC;
