-- Reported disk conditions only, not comprehensive hardware monitoring.
SELECT ASP_NUMBER, UNIT_NUMBER, RESOURCE_NAME,
       HARDWARE_STATUS, PROTECTION_STATUS
FROM QSYS2.SYSDISKSTAT
WHERE UNIT_NUMBER > 0
  AND
  (
      HARDWARE_STATUS IN
      ('DEGRADED', 'FAILED', 'HARDWARE FAILURE', 'NOT READY',
       'POWER LOSS', 'UNPROTECTED', 'READ WRITE PROTECTED',
       'WRITE PROTECTED', 'PARITY REBUILD')
      OR
      PROTECTION_STATUS IN
      ('DEGRADED', 'FAILED', 'HARDWARE FAILURE', 'NOT READY',
       'POWER LOSS', 'UNPROTECTED', 'READ WRITE PROTECTED',
       'WRITE PROTECTED', 'PARITY REBUILD', 'SUSPEND', 'RESUME PENDING')
  )
ORDER BY ASP_NUMBER, UNIT_NUMBER;
